/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.vectorfabrics;

/**
 * @author Jos
 * Java interface to the C-native DLL
 * This file is also used to generate the include file with the C function interfaces
 * that need to be implemented.
 * Such .h file is generated by executing from the testNative/src directory:
 * javah -verbose -classpath '.'com.vectorfabrics.vectorizeLib
 * this requires appending /c/Program Files/Java/jdk1.8.0_05/bin to the PATH
 * in the MinGW shell
 */
public class vectorizeLib {
    static {
        System.loadLibrary("VectorizedJNI"); // open native Vectorized.dll
    }
    public native String vectorizedVersionName();
    public native float vectorizedInproduct( int n, float a[], float b[]);
    public native float vectorizedAverage( int n, float a[]);
}
