/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vectorfabrics_vectorizeLib */

#ifndef _Included_com_vectorfabrics_vectorizeLib
#define _Included_com_vectorfabrics_vectorizeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vectorfabrics_vectorizeLib
 * Method:    vectorizedVersionName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedVersionName
  (JNIEnv *, jobject);

/*
 * Class:     com_vectorfabrics_vectorizeLib
 * Method:    vectorizedInproduct
 * Signature: (I[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedInproduct
  (JNIEnv *, jobject, jint, jfloatArray, jfloatArray);

/*
 * Class:     com_vectorfabrics_vectorizeLib
 * Method:    vectorizedAverage
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedAverage
  (JNIEnv *, jobject, jint, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
