/*
 * Jos van Eijndhoven, Vector Fabrics
 * The 'com_vectorfabrics_vectorizeLib.h' was generated by 'javah' from the java class interface
 */

#include "com_vectorfabrics_vectorizeLib.h"
#include "Vectorized.h"

extern "C" {
//const char * __stdcall vectorizedVersionName() {
//    Vectorized& veclib = VectorizedFactory::get();
//
//    return veclib.versionName();
//}

JNIEXPORT jstring JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedVersionName
  (JNIEnv *env, jobject obj) {
    Vectorized& veclib = VectorizedFactory::get();
    
    const char *name = veclib.versionName();
    return env->NewStringUTF(name);
}

//float __stdcall vectorizedInproduct( unsigned int n, const float *a, const float *b) {
//    Vectorized& veclib = VectorizedFactory::get();
//
//    return veclib.inproduct(n, a, a);
//}
JNIEXPORT jfloat JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedInproduct
  (JNIEnv *env, jobject obj, jint n, jfloatArray a, jfloatArray b) {
    Vectorized& veclib = VectorizedFactory::get();
    
    float *a_body = env->GetFloatArrayElements( a, 0);
    float *b_body = env->GetFloatArrayElements( b, 0);
    
    float r = veclib.inproduct(n, a_body, b_body);
    
    env->ReleaseFloatArrayElements( a, a_body, 0);
    env->ReleaseFloatArrayElements( b, b_body, 0);
    return (jfloat)r;
}

//float __stdcall vectorizedAverage( unsigned int n, const float *a) {
//    Vectorized& veclib = VectorizedFactory::get();
//
//	return veclib.average(n, a);
//}
JNIEXPORT jfloat JNICALL Java_com_vectorfabrics_vectorizeLib_vectorizedAverage
  (JNIEnv *env, jobject obj, jint n, jfloatArray a) {
    Vectorized& veclib = VectorizedFactory::get();
    
    float *a_body = env->GetFloatArrayElements( a, 0);
    
    float r = veclib.average(n, a_body);
    
    env->ReleaseFloatArrayElements( a, a_body, 0);
    return (jfloat)r;
}

}
